// Zusätzliche Musik-/Bar-Empfehlungen für die Route-66-Webkarte.
// Alle Einträge liegen im Filter "Musik / Bars".
window.musicBars = [
  { name: "Buddy Guy's Legends", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6307, 41.8675], text: "Musik / Bars · Chicago Blues Club" },
  { name: "Kingston Mines", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6601, 41.9316], text: "Musik / Bars · Legendärer Blues Club" },
  { name: "Blue Chicago", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6318, 41.8921], text: "Musik / Bars · Chicago Blues" },
  { name: "House of Blues Chicago", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6296, 41.8892], text: "Musik / Bars · Live Music Venue" },
  { name: "Reggies", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6245, 41.8535], text: "Musik / Bars · Rock / Blues / Americana" },
  { name: "The Hideout", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6509, 41.9074], text: "Musik / Bars · Americana / Indie / Alt Country" },
  { name: "Carol's Pub", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6684, 41.9399], text: "Musik / Bars · Country / Honky Tonk" },
  { name: "Rosa's Lounge", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.7072, 41.9091], text: "Musik / Bars · Authentic Chicago Blues" },
  { name: "Empty Bottle", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.7017, 41.9028], text: "Musik / Bars · Indie / Rock / Alternative" },
  { name: "AliveOne", type: "music", category: "Musik / Bars", city: "Chicago", coords: [-87.6637, 41.9397], text: "Musik / Bars · Jam Bar / Live Music" },
  { name: "Broadway Oyster Bar", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1913, 38.6195], text: "Musik / Bars · Blues / Jam / Rock" },
  { name: "Blueberry Hill Duck Room", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.3078, 38.6552], text: "Musik / Bars · Legendary Music Venue" },
  { name: "Old Rock House", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1989, 38.6184], text: "Musik / Bars · Rock / Americana" },
  { name: "BB's Jazz Blues and Soups", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1914, 38.6247], text: "Musik / Bars · Jazz / Blues" },
  { name: "Hammerstone's", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1998, 38.6108], text: "Musik / Bars · Soulard Blues Bar" },
  { name: "Venice Cafe", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.2035, 38.6042], text: "Musik / Bars · Local Music Spot" },
  { name: "Off Broadway", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.2215, 38.6104], text: "Musik / Bars · Americana / Folk" },
  { name: "1860 Saloon", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1988, 38.6106], text: "Musik / Bars · Soulard Blues" },
  { name: "The Honky Tonk STL", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1880, 38.6240], text: "Musik / Bars · Country / Honky Tonk" },
  { name: "The House Of Soul", type: "music", category: "Musik / Bars", city: "St. Louis", coords: [-90.1984, 38.6313], text: "Musik / Bars · Soul / Blues" },
  { name: "Mercury Lounge", type: "music", category: "Musik / Bars", city: "Tulsa", coords: [-95.9841, 36.1478], text: "Musik / Bars · Country / Blues" },
  { name: "Cain's Ballroom", type: "music", category: "Musik / Bars", city: "Tulsa", coords: [-95.9924, 36.1601], text: "Musik / Bars · Historic Country Venue" },
  { name: "The Colony", type: "music", category: "Musik / Bars", city: "Tulsa", coords: [-95.9485, 36.1276], text: "Musik / Bars · Open Stage / Songwriter" },
  { name: "Soundpony", type: "music", category: "Musik / Bars", city: "Tulsa", coords: [-95.9890, 36.1549], text: "Musik / Bars · Alternative / Local Scene" },
  { name: "LowDown", type: "music", category: "Musik / Bars", city: "Tulsa", coords: [-95.9895, 36.1542], text: "Musik / Bars · Jazz / Blues" },
  { name: "Medicine Park Tavern", type: "music", category: "Musik / Bars", city: "Lawton", coords: [-98.3950, 34.7305], text: "Musik / Bars · Local Music Bar" },
  { name: "Apache Casino Event Center", type: "music", category: "Musik / Bars", city: "Lawton", coords: [-98.3877, 34.6085], text: "Musik / Bars · Casino Concert Venue" },
  { name: "The Continental Club", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7498, 30.2475], text: "Musik / Bars · Austin Rock / Blues" },
  { name: "Antone's", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7432, 30.2672], text: "Musik / Bars · Legendary Blues Club" },
  { name: "The White Horse", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7219, 30.2607], text: "Musik / Bars · Honky Tonk / Country" },
  { name: "Broken Spoke", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7625, 30.2302], text: "Musik / Bars · Classic Texas Country" },
  { name: "Saxon Pub", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7621, 30.2505], text: "Musik / Bars · Singer Songwriter" },
  { name: "C-Boy's Heart & Soul", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7510, 30.2458], text: "Musik / Bars · Soul / Blues / Rock" },
  { name: "Hole in the Wall", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7268, 30.2963], text: "Musik / Bars · Rock Dive Bar" },
  { name: "Stubb's Bar-B-Q", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7365, 30.2685], text: "Musik / Bars · Outdoor Concert Venue" },
  { name: "Mohawk Austin", type: "music", category: "Musik / Bars", city: "Austin", coords: [-97.7399, 30.2669], text: "Musik / Bars · Indie / Rock" },
  { name: "Gruene Hall", type: "music", category: "Musik / Bars", city: "New Braunfels", coords: [-98.1392, 29.7392], text: "Musik / Bars · Legendary Texas Dance Hall" }
];
